id: I535ECC50
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T23:44:56+00:00'
last_modified: '2022-06-08T09:41:15.623049+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3405
  title: ཁ་ལེགས་སྤྲུལ་སྐུ་གོང་འོག་གི་གསུང་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    8F88:
      image_group_id: I3CN4379
      title: ''
      total_pages: 0
      order: 1
      base_file: 8F88.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
