id: P009250
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3405
  title: ཁ་ལེགས་སྤྲུལ་སྐུ་གོང་འོག་གི་གསུང་འབུམ།
  author: ''
  volumes:
    b171864b800443678428bf15635fbc4a:
      image_group_id: I3CN4379
      title: ''
      volume_number: 1
      total_pages: 0
    c34907d1a89647b1b0994252746fdcb9:
      image_group_id: I3CN4380
      title: ''
      volume_number: 2
      total_pages: 0
    4ad115334f714bd0bb957f0e031aaefc:
      image_group_id: I3CN4381
      title: ''
      volume_number: 3
      total_pages: 324
      base_file: v001.txt
